package com.myself.show.show.sql;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.myself.show.show.net.responceBean.TreeNode;
import com.myself.show.show.net.responceBean.User;
import com.myself.show.show.net.responceBean.Sheep;
import com.myself.show.show.net.responceBean.JoinUserWithSheep;
import com.myself.show.show.net.responceBean.UserInfo;
import com.myself.show.show.net.responceBean.LoginResponse;
import com.myself.show.show.net.responceBean.Cat;
import com.myself.show.show.net.responceBean.NoteDate;

import com.myself.show.show.sql.TreeNodeDao;
import com.myself.show.show.sql.UserDao;
import com.myself.show.show.sql.SheepDao;
import com.myself.show.show.sql.JoinUserWithSheepDao;
import com.myself.show.show.sql.UserInfoDao;
import com.myself.show.show.sql.LoginResponseDao;
import com.myself.show.show.sql.CatDao;
import com.myself.show.show.sql.NoteDateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig treeNodeDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig sheepDaoConfig;
    private final DaoConfig joinUserWithSheepDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig loginResponseDaoConfig;
    private final DaoConfig catDaoConfig;
    private final DaoConfig noteDateDaoConfig;

    private final TreeNodeDao treeNodeDao;
    private final UserDao userDao;
    private final SheepDao sheepDao;
    private final JoinUserWithSheepDao joinUserWithSheepDao;
    private final UserInfoDao userInfoDao;
    private final LoginResponseDao loginResponseDao;
    private final CatDao catDao;
    private final NoteDateDao noteDateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        treeNodeDaoConfig = daoConfigMap.get(TreeNodeDao.class).clone();
        treeNodeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        sheepDaoConfig = daoConfigMap.get(SheepDao.class).clone();
        sheepDaoConfig.initIdentityScope(type);

        joinUserWithSheepDaoConfig = daoConfigMap.get(JoinUserWithSheepDao.class).clone();
        joinUserWithSheepDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        loginResponseDaoConfig = daoConfigMap.get(LoginResponseDao.class).clone();
        loginResponseDaoConfig.initIdentityScope(type);

        catDaoConfig = daoConfigMap.get(CatDao.class).clone();
        catDaoConfig.initIdentityScope(type);

        noteDateDaoConfig = daoConfigMap.get(NoteDateDao.class).clone();
        noteDateDaoConfig.initIdentityScope(type);

        treeNodeDao = new TreeNodeDao(treeNodeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        sheepDao = new SheepDao(sheepDaoConfig, this);
        joinUserWithSheepDao = new JoinUserWithSheepDao(joinUserWithSheepDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        loginResponseDao = new LoginResponseDao(loginResponseDaoConfig, this);
        catDao = new CatDao(catDaoConfig, this);
        noteDateDao = new NoteDateDao(noteDateDaoConfig, this);

        registerDao(TreeNode.class, treeNodeDao);
        registerDao(User.class, userDao);
        registerDao(Sheep.class, sheepDao);
        registerDao(JoinUserWithSheep.class, joinUserWithSheepDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(LoginResponse.class, loginResponseDao);
        registerDao(Cat.class, catDao);
        registerDao(NoteDate.class, noteDateDao);
    }
    
    public void clear() {
        treeNodeDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        sheepDaoConfig.clearIdentityScope();
        joinUserWithSheepDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        loginResponseDaoConfig.clearIdentityScope();
        catDaoConfig.clearIdentityScope();
        noteDateDaoConfig.clearIdentityScope();
    }

    public TreeNodeDao getTreeNodeDao() {
        return treeNodeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public SheepDao getSheepDao() {
        return sheepDao;
    }

    public JoinUserWithSheepDao getJoinUserWithSheepDao() {
        return joinUserWithSheepDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public LoginResponseDao getLoginResponseDao() {
        return loginResponseDao;
    }

    public CatDao getCatDao() {
        return catDao;
    }

    public NoteDateDao getNoteDateDao() {
        return noteDateDao;
    }

}
